[package]
name = "rxstream"
version = "0.1.0"
authors = ["Yonghong Shi <yongshi@fb.com>"]
edition = "2018"
license = "MIT"

[dependencies]
tokio-timer = "0.2.10"
futures = "0.1.19"
tokio = "0.1.7"
either = "1.5.2"